# Generated by Django 3.1.7 on 2021-02-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0003_auto_20210227_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogers',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
